/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as PatientProfileRouteImport } from './routes/patient.profile'
import { Route as PatientLoginRouteImport } from './routes/patient.login'
import { Route as PatientAppointmentsRouteImport } from './routes/patient.appointments'
import { Route as DoctorScheduleRouteImport } from './routes/doctor.schedule'
import { Route as DoctorProfileRouteImport } from './routes/doctor.profile'
import { Route as DoctorPatientsRouteImport } from './routes/doctor.patients'
import { Route as DoctorLoginRouteImport } from './routes/doctor.login'
import { Route as DoctorAvailabilityRouteImport } from './routes/doctor.availability'
import { Route as PatientDoctorDoctorIdRouteImport } from './routes/patient.doctor.$doctorId'
import { Route as PatientBookDoctorIdRouteImport } from './routes/patient.book.$doctorId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/patient/',
  path: '/patient/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/doctor/',
  path: '/doctor/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/patient/profile',
  path: '/patient/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientLoginRoute = PatientLoginRouteImport.update({
  id: '/patient/login',
  path: '/patient/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientAppointmentsRoute = PatientAppointmentsRouteImport.update({
  id: '/patient/appointments',
  path: '/patient/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorScheduleRoute = DoctorScheduleRouteImport.update({
  id: '/doctor/schedule',
  path: '/doctor/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorProfileRoute = DoctorProfileRouteImport.update({
  id: '/doctor/profile',
  path: '/doctor/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPatientsRoute = DoctorPatientsRouteImport.update({
  id: '/doctor/patients',
  path: '/doctor/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorLoginRoute = DoctorLoginRouteImport.update({
  id: '/doctor/login',
  path: '/doctor/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorAvailabilityRoute = DoctorAvailabilityRouteImport.update({
  id: '/doctor/availability',
  path: '/doctor/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientDoctorDoctorIdRoute = PatientDoctorDoctorIdRouteImport.update({
  id: '/patient/doctor/$doctorId',
  path: '/patient/doctor/$doctorId',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientBookDoctorIdRoute = PatientBookDoctorIdRouteImport.update({
  id: '/patient/book/$doctorId',
  path: '/patient/book/$doctorId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/doctor/availability': typeof DoctorAvailabilityRoute
  '/doctor/login': typeof DoctorLoginRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/login': typeof PatientLoginRoute
  '/patient/profile': typeof PatientProfileRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/patient/book/$doctorId': typeof PatientBookDoctorIdRoute
  '/patient/doctor/$doctorId': typeof PatientDoctorDoctorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/doctor/availability': typeof DoctorAvailabilityRoute
  '/doctor/login': typeof DoctorLoginRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/login': typeof PatientLoginRoute
  '/patient/profile': typeof PatientProfileRoute
  '/doctor': typeof DoctorIndexRoute
  '/patient': typeof PatientIndexRoute
  '/patient/book/$doctorId': typeof PatientBookDoctorIdRoute
  '/patient/doctor/$doctorId': typeof PatientDoctorDoctorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/doctor/availability': typeof DoctorAvailabilityRoute
  '/doctor/login': typeof DoctorLoginRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/login': typeof PatientLoginRoute
  '/patient/profile': typeof PatientProfileRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/patient/book/$doctorId': typeof PatientBookDoctorIdRoute
  '/patient/doctor/$doctorId': typeof PatientDoctorDoctorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/doctor/availability'
    | '/doctor/login'
    | '/doctor/patients'
    | '/doctor/profile'
    | '/doctor/schedule'
    | '/patient/appointments'
    | '/patient/login'
    | '/patient/profile'
    | '/doctor/'
    | '/patient/'
    | '/patient/book/$doctorId'
    | '/patient/doctor/$doctorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/doctor/availability'
    | '/doctor/login'
    | '/doctor/patients'
    | '/doctor/profile'
    | '/doctor/schedule'
    | '/patient/appointments'
    | '/patient/login'
    | '/patient/profile'
    | '/doctor'
    | '/patient'
    | '/patient/book/$doctorId'
    | '/patient/doctor/$doctorId'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/doctor/availability'
    | '/doctor/login'
    | '/doctor/patients'
    | '/doctor/profile'
    | '/doctor/schedule'
    | '/patient/appointments'
    | '/patient/login'
    | '/patient/profile'
    | '/doctor/'
    | '/patient/'
    | '/patient/book/$doctorId'
    | '/patient/doctor/$doctorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DoctorAvailabilityRoute: typeof DoctorAvailabilityRoute
  DoctorLoginRoute: typeof DoctorLoginRoute
  DoctorPatientsRoute: typeof DoctorPatientsRoute
  DoctorProfileRoute: typeof DoctorProfileRoute
  DoctorScheduleRoute: typeof DoctorScheduleRoute
  PatientAppointmentsRoute: typeof PatientAppointmentsRoute
  PatientLoginRoute: typeof PatientLoginRoute
  PatientProfileRoute: typeof PatientProfileRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
  PatientIndexRoute: typeof PatientIndexRoute
  PatientBookDoctorIdRoute: typeof PatientBookDoctorIdRoute
  PatientDoctorDoctorIdRoute: typeof PatientDoctorDoctorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/patient'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/doctor'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/patient/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/login': {
      id: '/patient/login'
      path: '/patient/login'
      fullPath: '/patient/login'
      preLoaderRoute: typeof PatientLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/appointments': {
      id: '/patient/appointments'
      path: '/patient/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/schedule': {
      id: '/doctor/schedule'
      path: '/doctor/schedule'
      fullPath: '/doctor/schedule'
      preLoaderRoute: typeof DoctorScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/profile': {
      id: '/doctor/profile'
      path: '/doctor/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof DoctorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/patients': {
      id: '/doctor/patients'
      path: '/doctor/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof DoctorPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/login': {
      id: '/doctor/login'
      path: '/doctor/login'
      fullPath: '/doctor/login'
      preLoaderRoute: typeof DoctorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/availability': {
      id: '/doctor/availability'
      path: '/doctor/availability'
      fullPath: '/doctor/availability'
      preLoaderRoute: typeof DoctorAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/doctor/$doctorId': {
      id: '/patient/doctor/$doctorId'
      path: '/patient/doctor/$doctorId'
      fullPath: '/patient/doctor/$doctorId'
      preLoaderRoute: typeof PatientDoctorDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/book/$doctorId': {
      id: '/patient/book/$doctorId'
      path: '/patient/book/$doctorId'
      fullPath: '/patient/book/$doctorId'
      preLoaderRoute: typeof PatientBookDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DoctorAvailabilityRoute: DoctorAvailabilityRoute,
  DoctorLoginRoute: DoctorLoginRoute,
  DoctorPatientsRoute: DoctorPatientsRoute,
  DoctorProfileRoute: DoctorProfileRoute,
  DoctorScheduleRoute: DoctorScheduleRoute,
  PatientAppointmentsRoute: PatientAppointmentsRoute,
  PatientLoginRoute: PatientLoginRoute,
  PatientProfileRoute: PatientProfileRoute,
  DoctorIndexRoute: DoctorIndexRoute,
  PatientIndexRoute: PatientIndexRoute,
  PatientBookDoctorIdRoute: PatientBookDoctorIdRoute,
  PatientDoctorDoctorIdRoute: PatientDoctorDoctorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
